### PR TITLE
Use a modern pyproject.toml package structure

### LINKED ISSUE #159: Move project build infrastructure to pyproject.toml
https://packaging.python.org/en/latest/guides/writing-pyproject-toml/

pyproject.toml is fast becoming the preferred method for packaging python projects. We would like to move from setup-tools to this format.

### PR DESCRIPTION
**Pull request by wigging**
This adopts a modern `pyproject.toml` project structure for developing a Python package. The `setup.py`, `setup.cfg`, and `MANIFEST.in` files are no longer needed and have been removed. The zambeze package itself now resides in the `src` directory. All linting and formatting is now done with ruff instead of flake8 and black. The GitHub Actions workflows are also updated to account for these changes. Closes #159.

### CODE REVIEW

**Comment by wigging** [comment]
Someone needs to pull down this branch, create a new Python environment, install the package into that environment, make sure `pytest -m unit` passes, and make sure the `imagemagick_files.py` example runs correctly. I don't have any problems on my computer but I want to make sure someone else can run the tests and example before merging with main.

**Review by tskluzac — APPROVED** [review]
Without understanding fully what ruff does, I moreso reviewed code cleanliness and that the libraries included were necessary/complete. It does pass those checks, I figure we can merge and test in main.

**Comment by tskluzac** [comment]
> Someone needs to pull down this branch, create a new Python environment, install the package into that environment, make sure `pytest -m unit` passes, and make sure the `imagemagick_files.py` example runs correctly. I don't have any problems on my computer but I want to make sure someone else can run the tests and example before merging with main.

Just saw this comment. Will do!

**Comment by wigging** [comment]
To run the ruff linter/style checks use `ruff check .` and to run the ruff formatter checks use `ruff format --check .` where `.` is the top-level of this project. These are the same commands used in the `check.yml` workflow. I'll update `CONTRIBUTING.md` to utilize all the changes in this pull request.

**Comment by wigging** [comment]
I updated the contributing guidelines to account for the changes made in this pull request.

**Comment by wigging** [comment]
@tskluzac Have you had a chance to run the tests and examples in this branch?

**Comment by tskluzac** [comment]
> @tskluzac Have you had a chance to run the tests and examples in this branch?

Confirmed!

**Pull request merged**
