### PR TITLE
Clean up GitHub Actions workflows

### PR DESCRIPTION
**Pull request by wigging**
This pull request removes unnecessary workflows from GitHub Actions and cleans/fixes the failing workflows. The goal is to get a minimum set of linter checks, formatter checks, and unit tests to pass for pull requests. This will allow feature development to proceed with a reliable set of workflows. More workflows/checks can be added in a separate pull request.

### CODE REVIEW

**Comment by wigging** [comment]
@tskluzac How should we handle the Integration Tests which is the `integration-tests.yml` workflow? Can this workflow be completely deleted? If not, any suggestions to fix the missing modules? If it can be fixed, I suggest running it only on pull requests and not on every push event.

**Comment by wigging** [comment]
@tskluzac One of the checks that is failing is a Webhook that causes tests to run on a version of zambeze in the ORNL GitLab. Looks like Josh set this up. You can see all the webhooks by going to the Settings tab for this repository then to the Webhooks section. I'm going to delete this webhook unless there is a reason to keep it.

**Comment by wigging** [comment]
I went ahead and removed the globus tests but now other tests are failing 🤷‍♂️

**Comment by tskluzac** [comment]
Sorry, I don't see these since they write out to my personal email which I don't check during the work day. I'll try to change that habit... 

I will try to get the integration tests to pass. I'm going to reduce it to only execute the imagemagick example. 

You can delete the webhook you mentioned!

**Comment by wigging** [comment]
We can tackle the other failed checks related to the Docker compose workflows in a different pull request. I don't know what is causing the expected checks to appear in the list of items above the merge button. Otherwise, this is good enough for now and is a first step to cleaning up the workflows.

**Pull request merged**
