### PR TITLE
Standardize activity access structure so ImageMagick example will run consistently

### PR DESCRIPTION
**Pull request by tskluzac**
This pull request makes various changes so the imagemagick_files.py example will run consistently.

### CODE REVIEW

**Comment by wigging** [comment]
@tskluzac I made some changes to fix the test_activity_shell tests. The failure was related to the agent_id which I replaced with origin_agent_id. The example still runs on after making these changes so I don't think I screwed up the rest of the code with these changes.

**Comment by wigging** [comment]
@tskluzac What do you get on your end when you run `black --check .` for the branch associated with this pull request?

**Comment by wigging** [comment]
When I run `black --check .` on my computer for this branch, I get the following:

```
would reformat /Desktop/ORNL/FlowceptZambeze/zambeze/zambeze/orchestration/message/message_factory.py
would reformat /Desktop/ORNL/FlowceptZambeze/zambeze/zambeze/campaign/campaign.py

Oh no! 💥 💔 💥
2 files would be reformatted, 111 files would be left unchanged.
```

Which is different than what is reported in the Github Format Check:

```
would reformat /home/runner/work/Zambeze/Zambeze/zambeze/orchestration/message/message_factory.py
would reformat /home/runner/work/Zambeze/Zambeze/zambeze/orchestration/plugins_message_template_engine.py
would reformat /home/runner/work/Zambeze/Zambeze/zambeze/orchestration/plugins_message_validator.py

Oh no! 💥 💔 💥
3 files would be reformatted, 110 files would be left unchanged.
```

**Comment by wigging** [comment]
I fixed the format warnings from black that I was seeing on my computer. But it doesn't fix the Format Check warnings for `plugins_message_template_engine.py` and `plugins_message_validator.py` from the Github Actions workflow. I don't get format warnings for these files on my local machine.

**Comment by wigging** [comment]
The Format Check passes now but in my local environment I get the following errors:

```
would reformat /Desktop/ORNL/FlowceptZambeze/zambeze/zambeze/orchestration/plugins_message_template_engine.py
would reformat /Desktop/ORNL/FlowceptZambeze/zambeze/zambeze/orchestration/plugins_message_validator.py

Oh no! 💥 💔 💥
2 files would be reformatted, 111 files would be left unchanged.
```

I noticed the GitHub Action is using black 24.3 but in my local environment I'm using 23.11. The different versions are causing different format results which is why black may pass locally but fail in the GitHub Actions workflow and vice versa. We need to be using the same Python environment on our local machines and for Github Actions to avoid this type of problem. I'll create an issue about this so it can be addressed in a separate pull request.

**Comment by wigging** [comment]
@tskluzac Do you mind if I clean up the commits? There are several merge commits and other minor commits that can be squashed into one commit.

**Comment by tskluzac** [comment]
> @tskluzac Do you mind if I clean up the commits? There are several merge commits and other minor commits that can be squashed into one commit.

Sure thing -- is this just for cleaner book-keeping?

**Comment by tskluzac** [comment]
> What do you get on your end when you run `black --check .` for the branch associated with this pull request?

A little behind since I just got out of meeting-madness, but I received a message saying no files need reformatting.

**Comment by wigging** [comment]
> > @tskluzac Do you mind if I clean up the commits? There are several merge commits and other minor commits that can be squashed into one commit.
> 
> Sure thing -- is this just for cleaner book-keeping?

Yes, you don't need merge commits cluttering up the commit timeline. I use rebase instead of merge to avoid these extra commits.

**Review by wigging — APPROVED** [review]

**Pull request merged**
